name: Self Hosted Deployment

on:
  push:
    branches:
      - development
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Docker Image
        run: docker build -t node-api .

      - name: Stop Existing Container
        continue-on-error: true
        shell: powershell
        run: |
          docker stop node-api
          docker rm node-api

      - name: Start New Container
        shell: powershell
        run: |
          docker run -d `
            --name node-api `
            -p 3001:3000 `
            node-api

      - name: Verify Container
        shell: powershell
        run: |
          docker ps